name: Android CI
on:
  pull_request:
    branches: [development, main]
  push:
    branches: [development]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ hashFiles('android-app/**') != '' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Gradle build
        working-directory: android-app
        run: |
          chmod +x ./gradlew || true
          ./gradlew clean build --stacktrace
