name: Android CI

on:
  push:
    paths:
      - 'android-app/**'
      - '.github/workflows/android-ci.yml'
  pull_request:
    paths:
      - 'android-app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android-app   # ← run gradle inside android-app/

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21 (Gradle runtime)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager --install "platform-tools" \
                               "platforms;android-35" "build-tools;35.0.0" \
                               "platforms;android-34" "build-tools;34.0.0"

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug
        env:
          ANDROID_SDK_ROOT: ${{ env.ANDROID_HOME }}   # expose SDK to AGP
        run: ./gradlew --no-daemon clean assembleDebug

